
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRepository
{

using System;
    using System.Collections.Generic;
    
public partial class cape_reviews
{

    public int cape_id { get; set; }

    public Nullable<int> instructor_id { get; set; }

    public Nullable<int> course_id { get; set; }

    public Nullable<int> instructor_rating { get; set; }

    public string summary { get; set; }

    public Nullable<int> course_rating { get; set; }



    public virtual rating rating { get; set; }

}

}
