//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cse136Entities : DbContext
    {
        public cse136Entities()
            : base("name=cse136Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<cape_reviews> cape_reviews { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<course_preReq> course_preReq { get; set; }
        public virtual DbSet<course_schedule> course_schedule { get; set; }
        public virtual DbSet<enrollment> enrollments { get; set; }
        public virtual DbSet<instructor> instructors { get; set; }
        public virtual DbSet<instructor_type> instructor_type { get; set; }
        public virtual DbSet<rating> ratings { get; set; }
        public virtual DbSet<schedule_day> schedule_day { get; set; }
        public virtual DbSet<schedule_time> schedule_time { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TeachingAssistant> TeachingAssistants { get; set; }
        public virtual DbSet<TeachingAssistantType> TeachingAssistantTypes { get; set; }
        public virtual DbSet<grade_change> grade_change { get; set; }
        public virtual DbSet<preReq_Override> preReq_Override { get; set; }
    }
}
