
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IRepository
{

using System;
    using System.Collections.Generic;
    
public partial class preReq_Override
{

    public int preReq_Overrid_id { get; set; }

    public string student_id { get; set; }

    public int schedule_id { get; set; }

    public Nullable<bool> approved { get; set; }

}

}
